accept = [
  200, 201, 202, 203, 204,
  # Various anticrawlers :(
  403, 429,
  # Avoid being someone else's uptime monitor :)
  500, 504,
]
exclude = [
  '\/\/localhost',
  '\/\/127.0.0.1',
  '\/\/www.ssllabs.com',
  '\/\/www.imy.se',
  '\/\/packages.ubuntu.com',
  '\/\/regexr.com',
  '\/\/gdpr.fan',
  # The pages below fail AnchorCheck as they create
  # anchor's dynamically.
  '\/\/github.com',
  '\/\/registry.terraform.io',
  '\/\/kubespray.io',
  '\/\/www.oreilly.com',
  '\/\/inera.atlassian.net',
  # Too many redirects
  'https://admin.google.com/',
]
include-fragments = true
