---
name: deploy

"on":
  push:
    branches:
      - main
      - release-*
  schedule:
    # At 03:45 each day
    - cron: "45 3 * * *"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install Node dependencies
        run: npm ci

      - name: Install Python dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Configure Git user
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.${GITHUB_DOMAIN:-"github.com"}"
          git config --local user.name "${GITHUB_ACTOR}"

      - name: Configure Git user
        run: git fetch origin gh-pages --depth=1

      - name: Show CI environment for debugging
        run: |
          set -x

          id
          pwd

          git log -1
          git status

          cat /etc/lsb-release
          dpkg -l

          npm version
          npm ls

          python3 --version
          pip3 list

          set +x

      - id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.DOCS_APP_ID }}
          private-key: ${{ secrets.DOCS_PRIV_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            compliantkubernetes-apps

      - name: Fetch run id from apps
        id: fetch-run-id
        continue-on-error: true
        uses: actions/github-script@v8
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const { data: result } = await github.rest.actions.listWorkflowRuns({
              owner: ${{ github.repository_owner }},
              repo: 'compliantkubernetes-apps',
              workflow_id: 'tests.yml',
              branch: 'main',
              event: 'push',
              status: 'success'
            });

            if (result.total_count <= 0) {
              console.error("No action runs found")
              return 1
            }

            return result.workflow_runs[0].id

      - name: Download network policy artifact
        id: download-artifact
        continue-on-error: true
        if: steps.fetch-run-id.outcome == 'success'
        uses: actions/download-artifact@v5
        with:
          name: network-policy-values
          github-token: ${{ steps.app-token.outputs.token }}
          repository: ${{ github.repository_owner }}/compliantkubernetes-apps
          run-id: ${{ steps.fetch-run-id.outputs.result }}
          path: ./scripts/templates/

      - name: Template network policy docs
        if: steps.fetch-run-id.outcome == 'success' && steps.download-artifact.outcome == 'success'
        run: ./scripts/render-gomplate.sh

      - name: Auto-generate documentation
        run: ./scripts/jsonschema2md.py

      - name: Deploy with mike
        run: |
          if [ "$GITHUB_REF_NAME" == "main" ]; then
              # Latest version of the docs goes under https://elastisys.io/welkin
              VERSION_TITLE="main"
              VERSION="welkin"
          else
              # Other versions go under https://elastisys.io/welkin-v0.42/
              VERSION_TITLE=$(echo "$GITHUB_REF_NAME" | cut -d- -f2)
              VERSION="welkin-${VERSION_TITLE}"
          fi
          echo version: $VERSION version-title: $VERSION_TITLE
          mike deploy $VERSION -t $VERSION_TITLE --push --template overrides/redirect.html --alias-type redirect
          mike set-default welkin --push --template overrides/redirect.html
